[project]
name = "websitesummarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pooja Pathak", email = "pooja@skyfri.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "openai>=3.19.2",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
websitesummarizer = "websitesummarizer:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
